package com.uni.swms.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AIInsightAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAIInsightAllPropertiesEquals(AIInsight expected, AIInsight actual) {
        assertAIInsightAutoGeneratedPropertiesEquals(expected, actual);
        assertAIInsightAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAIInsightAllUpdatablePropertiesEquals(AIInsight expected, AIInsight actual) {
        assertAIInsightUpdatableFieldsEquals(expected, actual);
        assertAIInsightUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAIInsightAutoGeneratedPropertiesEquals(AIInsight expected, AIInsight actual) {
        assertThat(actual)
            .as("Verify AIInsight auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAIInsightUpdatableFieldsEquals(AIInsight expected, AIInsight actual) {
        assertThat(actual)
            .as("Verify AIInsight relevant properties")
            .satisfies(a -> assertThat(a.getType()).as("check type").isEqualTo(expected.getType()))
            .satisfies(a -> assertThat(a.getMessage()).as("check message").isEqualTo(expected.getMessage()))
            .satisfies(a -> assertThat(a.getConfidence()).as("check confidence").isEqualTo(expected.getConfidence()))
            .satisfies(a -> assertThat(a.getGeneratedAt()).as("check generatedAt").isEqualTo(expected.getGeneratedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAIInsightUpdatableRelationshipsEquals(AIInsight expected, AIInsight actual) {
        assertThat(actual)
            .as("Verify AIInsight relationships")
            .satisfies(a -> assertThat(a.getProduct()).as("check product").isEqualTo(expected.getProduct()));
    }
}
