package com.uni.swms.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class InventoryItemAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInventoryItemAllPropertiesEquals(InventoryItem expected, InventoryItem actual) {
        assertInventoryItemAutoGeneratedPropertiesEquals(expected, actual);
        assertInventoryItemAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInventoryItemAllUpdatablePropertiesEquals(InventoryItem expected, InventoryItem actual) {
        assertInventoryItemUpdatableFieldsEquals(expected, actual);
        assertInventoryItemUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInventoryItemAutoGeneratedPropertiesEquals(InventoryItem expected, InventoryItem actual) {
        assertThat(actual)
            .as("Verify InventoryItem auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInventoryItemUpdatableFieldsEquals(InventoryItem expected, InventoryItem actual) {
        assertThat(actual)
            .as("Verify InventoryItem relevant properties")
            .satisfies(a -> assertThat(a.getQuantity()).as("check quantity").isEqualTo(expected.getQuantity()))
            .satisfies(a -> assertThat(a.getLastUpdated()).as("check lastUpdated").isEqualTo(expected.getLastUpdated()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInventoryItemUpdatableRelationshipsEquals(InventoryItem expected, InventoryItem actual) {
        assertThat(actual)
            .as("Verify InventoryItem relationships")
            .satisfies(a -> assertThat(a.getProduct()).as("check product").isEqualTo(expected.getProduct()))
            .satisfies(a -> assertThat(a.getLocation()).as("check location").isEqualTo(expected.getLocation()));
    }
}
