package com.uni.swms.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SystemLogAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSystemLogAllPropertiesEquals(SystemLog expected, SystemLog actual) {
        assertSystemLogAutoGeneratedPropertiesEquals(expected, actual);
        assertSystemLogAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSystemLogAllUpdatablePropertiesEquals(SystemLog expected, SystemLog actual) {
        assertSystemLogUpdatableFieldsEquals(expected, actual);
        assertSystemLogUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSystemLogAutoGeneratedPropertiesEquals(SystemLog expected, SystemLog actual) {
        assertThat(actual)
            .as("Verify SystemLog auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSystemLogUpdatableFieldsEquals(SystemLog expected, SystemLog actual) {
        assertThat(actual)
            .as("Verify SystemLog relevant properties")
            .satisfies(a -> assertThat(a.getUsername()).as("check username").isEqualTo(expected.getUsername()))
            .satisfies(a -> assertThat(a.getAction()).as("check action").isEqualTo(expected.getAction()))
            .satisfies(a -> assertThat(a.getEntityName()).as("check entityName").isEqualTo(expected.getEntityName()))
            .satisfies(a -> assertThat(a.getDetails()).as("check details").isEqualTo(expected.getDetails()))
            .satisfies(a -> assertThat(a.getTimestamp()).as("check timestamp").isEqualTo(expected.getTimestamp()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSystemLogUpdatableRelationshipsEquals(SystemLog expected, SystemLog actual) {
        // empty method
    }
}
