package com.uni.swms.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class WarehouseLocationAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWarehouseLocationAllPropertiesEquals(WarehouseLocation expected, WarehouseLocation actual) {
        assertWarehouseLocationAutoGeneratedPropertiesEquals(expected, actual);
        assertWarehouseLocationAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWarehouseLocationAllUpdatablePropertiesEquals(WarehouseLocation expected, WarehouseLocation actual) {
        assertWarehouseLocationUpdatableFieldsEquals(expected, actual);
        assertWarehouseLocationUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWarehouseLocationAutoGeneratedPropertiesEquals(WarehouseLocation expected, WarehouseLocation actual) {
        assertThat(actual)
            .as("Verify WarehouseLocation auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWarehouseLocationUpdatableFieldsEquals(WarehouseLocation expected, WarehouseLocation actual) {
        assertThat(actual)
            .as("Verify WarehouseLocation relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getSection()).as("check section").isEqualTo(expected.getSection()))
            .satisfies(a -> assertThat(a.getCapacity()).as("check capacity").isEqualTo(expected.getCapacity()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWarehouseLocationUpdatableRelationshipsEquals(WarehouseLocation expected, WarehouseLocation actual) {
        // empty method
    }
}
